### ISSUE TITLE
Hello Methan

### ISSUE THREAD

**Issue by aaqil222** [SriMethan/Index#1]
What's an issue

**Comment by SriMethan** [comment]
Hello, Nothing is an issue.

**Comment by aaqil222** [comment]
Your lying

**Comment by SriMethan** [comment]
Nope, I'm true, this is just an empty repo.

**Comment by aaqil222** [comment]
Yeah that is the issue

**Comment by SriMethan** [comment]
Okay, will fix it soon.

**Comment by SriMethan** [comment]
Done, Do Check it out : [Index](https://srimethan.github.io/Index)
